apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-network-demo
  labels:
    app: cicd-network-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd-network-demo
  template:
    metadata:
      labels:
        app: cicd-network-demo
    spec:
      containers:
      - name: cicd-network-demo
        image: cicd-network-demo:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: CI
          value: "false"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-network-demo-service
spec:
  selector:
    app: cicd-network-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer