name: Update README Daily

on:
  schedule:
    - cron: "0 14 * * *"  # 17:00 по Москве (UTC+3)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          
      - name: Set UTF-8 encoding
        run: |
          echo "LANG=C.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=C.UTF-8" >> $GITHUB_ENV

      - name: Update README
        run: |
          echo "🔄 Запуск генератора README..."
          # Запускаем из корня репозитория
          go run ./utils/readme_updater/main.go
          echo "✅ README обновлен"
          
      - name: Commit and push changes
        run: |
          # Настраиваем Git
          git config --global user.name "README Bot"
          git config --global user.email "readme-bot@example.com"
          git config --global core.quotepath off
          
          # Добавляем изменения
          git add README.md utils/readme_updater/progress.json
          
          # Проверяем есть ли изменения
          if git diff --cached --quiet; then
            echo "⏭️ Нет изменений для коммита"
          else
            # Создаем коммит
            COMMIT_DATE=$(date +'%d.%m.%Y')
            git commit -m "Auto-update: Прогресс за $COMMIT_DATE"
            echo "💾 Создан коммит: Прогресс за $COMMIT_DATE"
            
            # Пробуем сделать push с повторными попытками
            ATTEMPT=1
            MAX_ATTEMPTS=3
            SUCCESS=false
            
            while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
              echo "🔄 Попытка пуша #$ATTEMPT..."
              if git pull --rebase origin main && git push origin main; then
                echo "✅ Успешный пуш после $ATTEMPT попытки"
                SUCCESS=true
                break
              else
                echo "❌ Ошибка пуша, попытка $ATTEMPT/$MAX_ATTEMPTS"
                ATTEMPT=$((ATTEMPT + 1))
                sleep 5
              fi
            done
            
            if [ "$SUCCESS" = false ]; then
              echo "❌ Критическая ошибка: не удалось выполнить пуш после $MAX_ATTEMPTS попыток"
              exit 1
            fi
          fi